import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, phone, message } = body;

    if (!name || !phone || !message) {
      return NextResponse.json(
        { error: "Missing required contact form fields (name, phone, message)." },
        { status: 400 }
      );
    }

    const adminEmail = process.env.ADMIN_EMAIL;
    const emailHost = process.env.EMAIL_HOST;
    const emailPort = process.env.EMAIL_PORT;
    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;

    if (!adminEmail) {
      console.warn("ADMIN_EMAIL is not configured in environment variables.");
      return NextResponse.json(
        { error: "configuration_error", message: "Admin Email (ADMIN_EMAIL) is not configured on the server." },
        { status: 500 }
      );
    }

    const emailSubject = `New Contact Form Inquiry from ${name}`;
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background: #fffaf4;">
        <h2 style="color: #3b2f2f; border-bottom: 2px solid #3b2f2f; padding-bottom: 10px; font-family: 'Poppins', sans-serif;">New Café Contact Inquiry</h2>
        <p style="font-size: 1rem; color: #555;">You have received a new contact inquiry from your website contact page.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px; background: #ffffff; border-radius: 4px; border: 1px solid #eee;">
          <tr>
            <td style="padding: 12px; font-weight: bold; width: 120px; border-bottom: 1px solid #eee; color: #3b2f2f;">Name:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee; color: #555;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; border-bottom: 1px solid #eee; color: #3b2f2f;">Phone:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee; color: #555;">${phone}</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; vertical-align: top; color: #3b2f2f;">Message:</td>
            <td style="padding: 12px; line-height: 1.5; color: #555;">${message}</td>
          </tr>
        </table>
        <hr style="border: 0; border-top: 1px solid #ddd; margin: 20px 0;" />
        <p style="font-size: 0.85rem; color: #777; text-align: center; margin: 0;">This email was automatically generated by your Café website contact form.</p>
      </div>
    `;

    // Check if SMTP configurations are provided. If not, log to console in development.
    if (!emailHost || !emailUser || !emailPass) {
      console.warn(
        "SMTP configurations (EMAIL_HOST, EMAIL_USER, EMAIL_PASS) are missing. Logging email content to server console:"
      );
      console.log("==================================================================");
      console.log(`TO: ${adminEmail}`);
      console.log(`SUBJECT: ${emailSubject}`);
      console.log(`BODY (HTML):\n${emailHtml}`);
      console.log("==================================================================");
      
      return NextResponse.json({
        success: true,
        message: "Contact form submitted successfully (development logging mode).",
      });
    }

    const port = emailPort ? parseInt(emailPort, 10) : 587;
    const secure = process.env.EMAIL_SECURE === "true" || port === 465;

    // Create SMTP transport
    const transporter = nodemailer.createTransport({
      host: emailHost,
      port: port,
      secure: secure,
      auth: {
        user: emailUser,
        pass: emailPass,
      },
    });

    // Send the email
    await transporter.sendMail({
      from: `"${name} (Café Contact Form)" <${emailUser}>`,
      to: adminEmail,
      subject: emailSubject,
      html: emailHtml,
    });

    return NextResponse.json({
      success: true,
      message: "Your message has been sent successfully to the café administrator.",
    });
  } catch (error: any) {
    console.error("Nodemailer send contact email failed:", error);
    return NextResponse.json(
      { error: "email_send_failed", message: error.message || "Failed to send contact email." },
      { status: 500 }
    );
  }
}
